
services:
  db:
    image: mysql:latest
    container_name: EasyChoresDBContainer
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - /Users/ianlau/db:/var/lib/mysql
