version: '3'
services:
  db:
    image: mysql:latest
    container_name: EasyChoresContainer
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Momizi494
      - MYSQL_DATABASE=easy-chores-db
    volumes:
      - /Users/ianlau/db:/var/lib/mysql